/**
 * badgeData.js — Client-side badge definitions (mirrors server badgeDefinitions.js)
 */

export const BADGE_CATEGORIES = {
    practice: {
        label: "Practice Badges",
        metric: "Total questions attempted",
        emoji: "⚔️",
        color: "#f59e0b",
        gradient: "from-amber-500 to-orange-600",
        bgClass: "bg-amber-500/10",
        borderClass: "border-amber-400/30",
        textClass: "text-amber-400",
        thresholds: [5, 15, 30, 60, 100, 175, 275, 400, 600, 1000],
        badges: [
            { name: "First Stepper", icon: "👣", desc: "Attempted your first 5 questions" },
            { name: "Practice Rookie", icon: "🌱", desc: "15 questions attempted" },
            { name: "Question Crusher", icon: "💥", desc: "30 questions crushed" },
            { name: "Skill Builder", icon: "🔨", desc: "60 questions — building real skill" },
            { name: "Concept Warrior", icon: "⚔️", desc: "100 questions conquered" },
            { name: "Problem Hunter", icon: "🎯", desc: "175 problems hunted down" },
            { name: "Relentless Solver", icon: "🔥", desc: "275 questions — you're relentless" },
            { name: "Master of Reps", icon: "🏋️", desc: "400 reps completed" },
            { name: "Practice Gladiator", icon: "🗡️", desc: "600 questions — a true gladiator" },
            { name: "Grandmaster of Grind", icon: "👑", desc: "1000 questions — ultimate grinder" },
        ],
    },
    streak: {
        label: "Streak Badges",
        metric: "Consecutive daily logins",
        emoji: "🔥",
        color: "#ef4444",
        gradient: "from-red-500 to-rose-600",
        bgClass: "bg-red-500/10",
        borderClass: "border-red-400/30",
        textClass: "text-red-400",
        thresholds: [1, 3, 5, 7, 14, 21, 30, 50, 75, 100],
        badges: [
            { name: "Day 1 Defender", icon: "🛡️", desc: "Logged in for the first time" },
            { name: "Routine Starter", icon: "📅", desc: "3-day streak" },
            { name: "Consistency Cadet", icon: "🎖️", desc: "5-day streak" },
            { name: "Habit Builder", icon: "🧱", desc: "7-day streak — a full week!" },
            { name: "Focused Fighter", icon: "🥊", desc: "14-day streak — two weeks strong" },
            { name: "Streak Guardian", icon: "🛡️", desc: "21-day streak — habit formed" },
            { name: "Time Tactician", icon: "⏰", desc: "30-day streak — one month!" },
            { name: "Discipline Knight", icon: "🏰", desc: "50-day streak" },
            { name: "Iron Will Champion", icon: "💎", desc: "75-day streak — iron discipline" },
            { name: "Eternal Flame Legend", icon: "🔥", desc: "100-day streak — legendary" },
        ],
    },
    learning: {
        label: "Learning Badges",
        metric: "Stories + BrainBoards completed",
        emoji: "📚",
        color: "#8b5cf6",
        gradient: "from-purple-500 to-violet-600",
        bgClass: "bg-purple-500/10",
        borderClass: "border-purple-400/30",
        textClass: "text-purple-400",
        thresholds: [1, 3, 5, 10, 20, 35, 50, 75, 100, 150],
        badges: [
            { name: "Curious Mind", icon: "🧠", desc: "Completed your first learning item" },
            { name: "Knowledge Seeker", icon: "🔍", desc: "3 items completed" },
            { name: "Concept Explorer", icon: "🧭", desc: "5 items explored" },
            { name: "Topic Tamer", icon: "🦁", desc: "10 topics tamed" },
            { name: "Subject Strategist", icon: "📋", desc: "20 subjects mastered" },
            { name: "Idea Architect", icon: "🏗️", desc: "35 ideas built" },
            { name: "Theory Titan", icon: "⚡", desc: "50 theories conquered" },
            { name: "Wisdom Warrior", icon: "🗡️", desc: "75 wisdom points" },
            { name: "Scholar Supreme", icon: "🎓", desc: "100 — a supreme scholar" },
            { name: "Omniscient Legend", icon: "👁️", desc: "150 — omniscient status" },
        ],
    },
    accuracy: {
        label: "Accuracy Badges",
        metric: "Total correct answers",
        emoji: "🎯",
        color: "#10b981",
        gradient: "from-emerald-500 to-green-600",
        bgClass: "bg-emerald-500/10",
        borderClass: "border-emerald-400/30",
        textClass: "text-emerald-400",
        thresholds: [3, 10, 25, 50, 100, 175, 275, 400, 600, 1000],
        badges: [
            { name: "Careful Learner", icon: "🌿", desc: "3 correct answers" },
            { name: "Sharp Shooter", icon: "🎯", desc: "10 correct answers" },
            { name: "Precision Player", icon: "🎮", desc: "25 correct" },
            { name: "Error Eliminator", icon: "🧹", desc: "50 correct" },
            { name: "Focus Specialist", icon: "🔬", desc: "100 correct" },
            { name: "Smart Solver", icon: "💡", desc: "175 correct" },
            { name: "Accuracy Ace", icon: "🃏", desc: "275 correct" },
            { name: "Zero-Mistake Ninja", icon: "🥷", desc: "400 correct" },
            { name: "Precision Master", icon: "🏆", desc: "600 correct" },
            { name: "Flawless Legend", icon: "👑", desc: "1000 correct — flawless" },
        ],
    },
};

export const CATEGORY_ORDER = ["practice", "streak", "learning", "accuracy"];
